### ISSUE TITLE
Add/Verify Python3.7/Django2.2 support.

### ISSUE THREAD

**Issue by haykd** [AdvancedThreatAnalytics/django-otp-sns#1]
We need to add/verify support for:
* [ ] Python 3.7
* [ ] Django 2.2

**Comment by oleksandr-potapov** [comment]
@haykd Tested with Python 3.7.5 And Django2.2.7. Everything works as expected, no changes needed.

**Comment by haykd** [comment]
@oleksandr-potapov thanks.
